name: OCR Mazeppa Fraktur

on:
  workflow_dispatch:

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr tesseract-ocr-deu-frak poppler-utils qpdf pandoc

    - name: Extract pages 7–16
      run: |
        mkdir pages
        qpdf "Mazeppa 1.pdf" --pages . 7-16 -- pages/mazeppa_excerpt.pdf

    - name: Run OCR with Tesseract (Fraktur)
      run: |
        mkdir output
        tesseract pages/mazeppa_excerpt.pdf output/mazeppa_ocr -l deu-frak --psm 1 pdf

    - name: Convert PDF to DOCX
      run: |
        pandoc ou
