name: OCR Mazeppa Fraktur

on:
  workflow_dispatch:

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr qpdf poppler-utils pandoc curl

    - name: Install Fraktur language model manually
      run: |
        sudo mkdir -p /usr/share/tesseract-ocr/tessdata
        sudo curl -L -o /usr/share/tesseract-ocr/tessdata/deu-frak.traineddata \
          https://github.com/tesseract-ocr/tessdata/raw/main/deu-frak.traineddata

    - name: Extract pages 7–16
      run
