name: OCR Mazeppa Fraktur (deu_latf)

on:
  workflow_dispatch:

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr qpdf poppler-utils pandoc curl

    - name: Download deu_latf.traineddata
      run: |
        sudo mkdir -p /usr/share/tesseract-ocr/tessdata
        sudo curl -L -o /usr/share/tesseract-ocr/tessdata/deu_latf.traineddata \
          https://github.com/tesseract-ocr/tessdata_best/raw/main/deu_latf.traineddata

    - name: Extract pages 7–16 as PDF
      run: |
        mkdir pages
        qpdf "Mazeppa 1.pdf" --pages . 7-16 -- pages/mazeppa_excerpt.pdf

    - name: Convert PDF pages to images
      run: |
        mkdir images
        pdftoppm -tiff pages/mazeppa_excerpt.pdf images/page

    - name: Run OCR with Tesseract (deu_latf) on all images
      run: |
        mkdir output
        for img in images/page*.tiff; do \
          tesseract "$img" "output/$(basename "$img" .tiff)" -l deu_latf --tessdata-dir /usr/share/tesseract-ocr/tessdata --psm 1 txt; \
        done
        cat output/*.txt > output/mazeppa_ocr.txt

    - name: Convert TXT to DOCX
      run: |
        pandoc output/mazeppa_ocr.txt -o ocr/mazeppa_1_pages7-16.docx

    - name: Commit and push result
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ocr/mazeppa_1_pages7-16.docx
        git commit -m "Add OCR result for pages 7–16 of Mazeppa 1 (deu_latf)"
        git push
