name: OCR Mazeppa Fraktur

on:
  workflow_dispatch:

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr tesseract-ocr-deu-frak poppler-utils pandoc

    - name: Extract pages 7–16
      run: |
        mkdir pages
        pdftk "Mazeppa 1.pdf" cat 7-16 output pages/mazeppa_excerpt.pdf

    - name: Run OCR with Tesseract (Fraktur)
      run: |
        mkdir output
        tesseract pages/mazeppa_excerpt.pdf output/mazeppa_ocr -l deu-frak --psm 1 pdf

    - name: Convert PDF to DOCX
      run: |
        pandoc output/mazeppa_ocr.pdf -o ocr/mazeppa_1_pages7-16.docx

    - name: Commit and push result
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ocr/mazeppa_1_pages7-16.docx
        git commit -m "Add OCR result for pages 7–16 of Mazeppa 1 (Fraktur)"
        git push
